name: Jacob's Trunk Based Development Deployment

on:
  push:
    branches:
    - main
    tags:
      - '*'  # Trigger on any tag change

env:
  BUCKET_NAME : ${{ secrets.AWS_BUCKET }}
  IAM_ROLE: ${{ secrets.IAM_ROLE }}
  AWS_REGION : "us-east-1"

# permission can be added at job level or workflow level    
permissions:
      id-token: write
      contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
    
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Zip Files
        run: |
          touch test_file.md

        # simulate some sort of deployment
      - name: Deploy to S3
        env:
            aws_bucket: ${{ secrets.AWS_BUCKET }}
        run: |
            if [ "${{ github.ref_type }}" == "tag" ]; then
                aws s3 cp test_file.md s3://$aws_bucket-prod/
            else
                aws s3 cp test_file.md s3://$aws_bucket-stg/
            fi