name: Development Environment Deployment

on:
  pull_request_review:
    types: [submitted, dismissed]
  workflow_dispatch:
    inputs:
        dev_environment:
            description: 'Development Environment to deploy to'
            required: true
            default: 'dev-1'
            type: string

jobs:
  deploy_to_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

        # simulate some sort of deployment
      - name: "Deploy to ${{ github.event.inputs.dev_environment }}"
        run: |
            echo "Deploying to ${{ github.event.inputs.dev_environment }}"
            touch test_file.md
            echo "Deployed to ${{ github.event.inputs.dev_environment }}"