name: Production Release

on:
    push:
        branches:
        - main
        tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    # simulate some sort production deployment
    # this could be a new docker push to production, or maybe you're promoting the latest staging docker image to production

    # docker pull your-account-id.dkr.ecr.your-region.amazonaws.com/your-repo-name:staging
    # docker tag your-account-id.dkr.ecr.your-region.amazonaws.com/your-repo-name:staging your-account-id.dkr.ecr.your-region.amazonaws.com/your-repo-name:production
    # docker push your-account-id.dkr.ecr.your-region.amazonaws.com/your-repo-name:production
    - name: "Deploy to Production"
      run: |
        echo "Deploying to Production"
        touch test_file.md
        echo "Production Deploy Complete"